### ISSUE TITLE
hi Klougz , when i run your code, i get a trouble , can you fix ?

### ISSUE THREAD

**Issue by KalvinThien** [Klouqz/AI-powered-WordPress-Article-Generator-Automating-Content-Creation#1]
AI-Powered-WordPress-Article-Generator-main\main.py", line 74, in start
    start.generate()
AI-Powered-WordPress-Article-Generator-main\publisher\main.py", line 31, in generate
    self.post(keyword[1])
AI-Powered-WordPress-Article-Generator-main\publisher\main.py", line 49, in post
    wp_publish.publish()
AI-Powered-WordPress-Article-Generator-main\publisher\wp_publish.py", line 22, in publish
    json_data = json.loads(response.text)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Glimor** [comment]
Hi. I' ll fix it in 10 days. Thanks for your feedback.
