### ISSUE TITLE
Can not publish post

### ISSUE THREAD

**Issue by imanseptian** [Klouqz/AI-powered-WordPress-Article-Generator-Automating-Content-Creation#2]
Hi @Klouqz , I try your app. It run smoothly. But it failed to post it in my wordpress website.

I use Wordpress 6.3

Can you help? Thanks

**Comment by Glimor** [comment]
Hi @imanseptian, did u create API key on your wordpress website?

**Comment by imanseptian** [comment]
Yes, I use API key with the default rest API, like this: https://mywebsite.com/wp-json

**Comment by Glimor** [comment]
Can you write the error you get?

**Comment by imanseptian** [comment]
There's no error information on the terminal. It says that the article was published and enter the sleep period. But the article never publish nor draft in my website. 

I also tried modifying the wp_publish.py according to rest api guidelines I've found in the internet. Still no luck.

**Comment by Glimor** [comment]
I'll check it for you when I'm free. Thank you for feedback.
